<?php

/**
 * Implements hook_composer_json_alter().
 *
 * This hook filters out dependencies loaded by the skeleton project's
 * composer.json files and its dependencies.
 *
 * @param $json
 */
function composerplatformsupport_composer_json_alter(&$json) {

  // These are merged in composer_manager_build_json, except we don't need
  // to filter repositories.
  foreach (array('require', 'require-dev', 'conflict', 'replace', 'provide', 'suggest') as $key) {
    foreach (\Composed\package_configs($key) as $config) {
      // Remove already-installed packages from the JSON.
      $json[$key] = array_diff_assoc((array) $json[$key], $config);
    }
  }

  foreach (\Composed\package_configs('autoload') as $config) {
    foreach ($config as $key => $value) {
      $json['autoload'][$key] = array_diff_key((array) $json['autoload'][$key], $value);
    }
  }

  // Remove empty autoload configurations.
  $json['autoload'] = array_filter($json['autoload']);
  $json = array_filter($json);
}

/**
 * Implements hook_js_alter().
 */
function composerplatformsupport_js_alter(&$javascript) {
  if (module_exists('statistics') &&
    variable_get('statistics_count_content_views', 0) &&
    variable_get('statistics_count_content_views_ajax', 0) &&
    isset($javascript['settings'])) {
    foreach ($javascript['settings']['data'] as &$js) {
      if (isset($js['statistics'])
        && $js['statistics']['url'] === url(drupal_get_path('module', 'statistics') . '/statistics.php')) {
        $js['statistics']['url'] = url('statistics.php');
      }
    }
  }
}
